MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://Caffe2Detectron/COCO/35857197/e2e_faster_rcnn_R-50-C4_1x"
DATASETS:
  TEST: ("coco_2017_val",)
  TRAIN: ("coco_2017_val",)
TEST:
  IMS_PER_BATCH: 1  # for 1GPUs
