MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    NUM_CLASSES: 501
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATALOADER:
  SIZE_DIVISIBILITY: 32
  NUM_WORKERS: 4
DATASETS:
  TRAIN: ("oid_v5_challenge_train_expanded",)
  TEST: ("oid_v5_challenge_val_expanded",)
  SUBMIT: ("oid_v5_challenge_test",)
#  SUBSET: ("no_group_of", "leaves", "groupByCount_0_500", "groupByTopic_5_1")
SOLVER:
    BASE_LR: 0.02
    WEIGHT_DECAY: 0.0001

    ## 1 EPOCH 16 BATCH
    #STEPS: (70000, 100000)
    #MAX_ITER: 110000

    # 5 EPOCH 16 BATCH  
    #STEPS: (350000, 500000)
    #MAX_ITER: 550000

    USE_SCHEDULER_DATA_DEPENDENT: 1
    MAX_EPOCHS: 1
#TEST:
#  BBOX_AUG:
#    ENABLED: True
#    H_FLIP: True
#    SCALES: (400, 500, 600, 700, 900, 1000, 1100, 1200)
#    MAX_SIZE: 2000
#    SCALE_H_FLIP: True
