MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://Caffe2Detectron/COCO/37129812/e2e_mask_rcnn_X-152-32x8d-FPN-IN5k_1.44x"
  BACKBONE:
    CONV_BODY: "R-152-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
    STRIDE_IN_1X1: False
    NUM_GROUPS: 32
    WIDTH_PER_GROUP: 8
    STAGE_WITH_DCN: (False, True, True, True)
    WITH_MODULATED_DCN: True
    DEFORMABLE_GROUPS: 1
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TRAIN: 2000
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 1000
    FPN_POST_NMS_TOP_N_TEST: 1000
  ROI_HEADS:
    USE_FPN: True
  ROI_BOX_HEAD:
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
DATALOADER:
  SIZE_DIVISIBILITY: 32
SOLVER:
    #BASE_LR: 0.02
    #WEIGHT_DECAY: 0.0001
    ## 1 EPOCH 16 BATCH
    STEPS: (60000, 80000)
    MAX_ITER: 90000

    # 5 EPOCH 16 BATCH
    #STEPS: (350000, 500000)
    #MAX_ITER: 550000

#    USE_SCHEDULER_DATA_DEPENDENT: 1
#    MAX_EPOCHS: 12

INPUT:
  # Size of the smallest side of the image during training
  MIN_SIZE_TRAIN: (600,)  # (800,)
  # Maximum size of the side of the image during training
  MAX_SIZE_TRAIN: 800
