MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "http://storage.googleapis.com/public-models/efficientnet-b3-c8376fa2.pth"
  #ROI_BOX_HEAD:
  #    FEATURE_EXTRACTOR: "EfficientNetROIFeatureExtractor"
  BACKBONE:
      CONV_BODY: 'E-B3'
  RESNETS:
    BACKBONE_OUT_CHANNELS: 384
    RES2_OUT_CHANNELS: 96
  RPN:
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  STEPS: (1200, 1600)
  MAX_ITER: 2000
