MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "http://storage.googleapis.com/public-models/efficientnet-b0-08094119.pth"
  BACKBONE:
      CONV_BODY: 'E-B0'
  RESNETS:
    BACKBONE_OUT_CHANNELS: 320
    RES2_OUT_CHANNELS: 80
  RPN:
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (120000, 160000)
  MAX_ITER: 180000
INPUT:
    PIXEL_MEAN: [0.485, 0.456, 0.406] # [102.9801, 115.9465, 122.7717]
    PIXEL_STD: [0.229, 0.224, 0.225] # [1., 1., 1.]
    TO_BGR255: False
OUTPUT_DIR: "output"
