MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "http://storage.googleapis.com/public-models/efficientnet-b5-586e6cc6.pth"
  #ROI_BOX_HEAD:
  #    FEATURE_EXTRACTOR: "EfficientNetROIFeatureExtractor"
  BACKBONE:
      CONV_BODY: 'E-B5'
  RESNETS:
    BACKBONE_OUT_CHANNELS: 384
    RES2_OUT_CHANNELS: 96
  RPN:
    PRE_NMS_TOP_N_TRAIN: 6000
    PRE_NMS_TOP_N_TEST: 1000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  #BASE_LR: 0.02
  WEIGHT_DECAY: 0.0001
  #STEPS: (1200, 1600)
  #MAX_ITER: 2000

  #WARMUP_FACTOR: 0.1


  # 1 GPU:
  BASE_LR: 0.0025
  MAX_ITER: 1200
  STEPS: [0, 600, 800]
  IMS_PER_BATCH: 2  # for 1GPUs

  # 8 GPUs:
#   BASE_LR: 0.02
#   MAX_ITER: 150
#   STEPS: [0, 75, 100]
#  IMS_PER_BATCH: 16  # for 8GPUs
