MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "http://storage.googleapis.com/public-models/efficientnet-b0-08094119.pth"
  RPN_ONLY: True
  BACKBONE:
      CONV_BODY: 'E-B0-FPN'
  RESNETS:
    BACKBONE_OUT_CHANNELS: 320
    RES2_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    PRE_NMS_TOP_N_TEST: 1000
    POST_NMS_TOP_N_TEST: 2000
    FPN_POST_NMS_TOP_N_TEST: 2000
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  # 8 GPU
#  BASE_LR: 0.02
#  WEIGHT_DECAY: 0.0001
#  STEPS: (60000, 80000)
#  MAX_ITER: 90000
#  IMS_PER_BATCH: 16
  # 1 GPU
  BASE_LR: 0.0025
  WEIGHT_DECAY: 0.0001
  STEPS: (480000, 640000)
  MAX_ITER: 720000
  IMS_PER_BATCH: 2
INPUT:
    PIXEL_MEAN: [0.485, 0.456, 0.406] # [102.9801, 115.9465, 122.7717]
    PIXEL_STD: [0.229, 0.224, 0.225] # [1., 1., 1.]
    TO_BGR255: False
OUTPUT_DIR: "output_rpn"
